### ISSUE TITLE
Module requires main queue setup since it overrides `init`.

### ISSUE THREAD

**Issue by malashkevich** [greenfrvr/react-native-window-guard#1]
There is warning on iOS.
"Module WindowInsetsModule requires main queue setup since it overrides constantsToExport but doesn't implement requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of."

**Comment by greenfrvr** [comment]
Thanks. The issue is fixed an issue in v.1.0.0.
