### ISSUE TITLE
Needs autolinking to support React 0.60.x

### ISSUE THREAD

**Issue by sudomann** [greenfrvr/react-native-window-guard#5]
React 0.60.x brings about automatic linking, and this package still requires the manual use of the `react-native link` command during setup. Currently, `react-native` prints a warning upon use of `link`.

[I wish I had experience with Gradle and Cocoapods configuration so I could help out with this.](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md)

**Comment by greenfrvr** [comment]
Fixed in v1.0.4
