### ISSUE TITLE
Property types and autocomplete

### ISSUE THREAD

**Issue by artyorsh** [greenfrvr/react-native-window-guard#7]
For the better development experience, it would be nice to have a [Flow](https://flow.org/) / [prop-types](https://github.com/facebook/prop-types) or .d.ts generated and published to [DefinitlyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

![image](https://user-images.githubusercontent.com/10753921/62700639-1b6b9800-b9eb-11e9-870d-7864d7cf9cd1.png)

**Comment by greenfrvr** [comment]
Added in v1.0.5
